### ISSUE TITLE
White screen bug

### ISSUE THREAD

**Issue by EmanueleCoppola** [darkwave/mbot-scratch-blocks#2]
While using this software I experienced many crashes.
I'd say "white screen" rather than crashes.
This after placing many blocks randomly (normal kid usage). To reproduce it you should use this software so much (haven't figured out any sequence to reproduce it yet).

**Comment by darkwave** [comment]
This issue was caused by sensor event triggered while adding a new block with field value (like _move forward_)... Fixed it :relaxed:
